version: '3.8'

services:
  waf:
    image: owasp/modsecurity-crs:4.12.0-nginx-alpine-202503230103
    container_name: waf
    restart: unless-stopped
    network_mode: "host"
    environment:
      - BACKEND=${BACKEND}
      - BLOCKING_PARANOIA=${BLOCKING_PARANOIA}
    ports:
      - "9443:8443"
      - "9080:8080"
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080 || curl -f http://localhost:8443"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      autoheal: "true"

  autoheal:
    image: willfarrell/autoheal
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      AUTOHEAL_CONTAINER_LABEL: "autoheal"
      AUTOHEAL_INTERVAL: "30"
      AUTOHEAL_START_PERIOD: "120"
      AUTOHEAL_DEFAULT_STOP_TIMEOUT: "10"
